name: sturm
version: 0.0.0
description: Universal functional stream handling
author:
- "Te Standby <testandby@gmail.com>"
license: LGPLv3
private: true

main: lib/index.js
repository: "ismo-js/sturm"
dependencies: {}
devDependencies:
  gulp: "~3.9.1"
  gulp-yaml: "~1.0.1"
